#+Author: Britt Anderson
#+bibliography:/home/britt/gitRepos/masterBib/bayatt.bib
#+csl-style: ../admin/cambridge-university-press-numeric.csl
#+options: ^:nil toc:nil d:nil
#+Title: Abstraction and Cognitive Neuroscience Modeling
#+Date: Winter 2022

  #+begin_quote
  The purpose of abstraction is not to be vague, but to create a new semantic level in which one can be absolutely precise. --- Edsger Dijkstra [fn:1]
  #+end_quote

* Some Motivating Thoughts and a Brief Resumé

We want a model of mind and we think that its form should be computational. We have reviewed what we mean by mind, and by computation, and what we mean by a computational mind. Next we dissected what it means for something to be a theory so that the account we offer can be scientifically useful.

From these considerations we are led to mathematics. Math is the language for the formal unambiguous description of processes linking mind and computation, e.g., computation proper, information processing, statistics, and manifolds.

In considering these different areas of math we have several desiderata. We would like to be able to express clearly and unambiguously theories of mind in the most apt mathematical language. We would like the choice of that phrasing and selection to facilitate the translation into programming language form for simulating its consequences. To do all that we will benefit from considering meta-mathematical themes. What are some of the terms and ways of thinking that permeate mathematics and the way mathematicians talk, write, and conceive what it is they do.

Our introduction to the thinking about how it is that mathematicians think about what it is they do so that we can use their products for our own purposes starts with the idea of /abstraction/.

*What is /abstraction/?*

* Warm-up Questions

Ask yourself:

1. Is the only acceptable fate of a theory of mind to be reduced to a theory of the brain?
   Can we think /abstractly/ about mental operations and their transformations without ever needing to reduce the mental to the neural?

2. Can we relate neural and mental constructs currently? Clearly? Concisely? Unambiguously?
   In /[[file:category-day.org][category theory]]/ there is the notion of a /functor/. Can we /abstractly/ conceive of a realm of mental objects that interact via some sort of connection, and a different "world" of neural objects [fn:2] with links between them, and specify a /functorial/ connection that relates the abstracts objects and linkages of our mental and neural categories? Do we gain by so doing?

3. Do we need a new vocabulary or new tools?
   If we are open to the idea of /abstraction/ as a powerful tool for our theoretical entreprise do we need a new language for its expression?

4. If we think about expressing the population of neuronal firing rates as a vector do we derive any benefits from invoking "vector spaces?"
   This is meant to be a concrete example of /abstraction/. We are introduced to vectors by comparing them to arrows. Entities with size and direction (magnitude and orientation). Given a set of /basis/ vectors we can imagine all the possible vectors we could construct from those elements by combining them and growing or shrinking them. Imagine that we construct that /vector space/. Now instead of thinking of indivdual vectors can we instead think of vector spaces? That is an example of abstraction? Does it help our theoretical goals or un-necessarily complicate the activity? What do we gain and what do we lose?

* Target Reading: Computing With Cognitive States
  There is not a mathematics of abstraction. Modern mathematics is largely the practice of abstraction; a pursuit of new semantic levels above those that came before that allow precise talk for collections and highlight their similarities from this new higher perspective.

  To practice thinking about abstraction, to give an example of it, and to examine how well it contributes to our goal of facilitating computational expressions via programs I have selected a recent article talking about computing with cognitive states. We can discuss whether the model of memory here is a good one or not, but more critical will be our assessment of how the practice of abstraction helps or hinders. We will practice abstraction in our assessment: judging the success not by the specific concrete model of memory, but by the abstract framing as cognitive states and an algebra.
  
** Activity :class_activity:

*** Reading
    Make sure you read before class our target article [[cite:&reimann21_comput_with_cognit_states]]. We will be talking about this article and implementing the model it describes.
    
*** Questions From the Reading:
  1. What is the meaning of the word algebra here?

  2. What is a "metric?"

  3. Why does Reiman describe cosine similarity (and what is that) as local and his measure of similarity as global? Why might you want to chose one or the other?

  4. Is this paper describing a theory (in the way we talked about it earlier)?
     
  5. How does the brain figure into the theory here?

  6. How does the development of ideas here relate to the mind - theory - math - code trajectory I proposed as useful?

  7. What language would be a good one for coding up this model?

  8. What critiques do you have of this model specifically (as opposed to the general outline that we just discussed)?

  9. What would be gained by making a model of this with spiking elements?

*** Programming Activity From the Reading:

This is an assignment that we will review and talk about at the start of next class session. You have the rest of today and until next class to work on it in your groups.

Create as much code as you can that implements your understanding of the model described. If you have the time you can also add some code for doing simple simulations of the model in operation and plotting the results.

To get credit for this assignment you will need to place a message in the dropbox on Learn reporting that you have initiated a pull request to the course github repo. Your code should go in the appropriate sub-directory of ~mind-theory-math-code/code/computing-with-cog-states~. Your sub-directory in the github repo should also include a short prose report of your main impressions on trying to implement this model using your test language. 

*** Working comments
:working-comments:
Does his measure of similarity scale well with dimensionality?
:END:



* Optional Additional Readings

A more detailed study of computational models of memory [[cite:&howard22_formal_model_memor_based_tempor_varyin_repres]]



* References
[[bibliography:/home/britt/gitRepos/masterBib/bayatt.bib]]

* Footnotes
[fn:2] These too might be thought of abstractly as spike trains or vectors of neural firing rates.  

[fn:1] The [[https://en.wikipedia.org/wiki/Edsger_W._Dijkstra][theoretical computer scientist]] who did most of his computer science work with a fountain pen.  
