#+Title: Dynamics and Information
#+Author: Britt Anderson
#+Date: Winter 2022
#+bibliography:/home/britt/gitRepos/masterBib/bayatt.bib
#+csl-style: ../admin/cambridge-university-press-numeric.csl
#+options: ^:nil toc:nil d:nil

* Old Business
  1. Projects
  2. Manifold Comments/Questions
     An interesting article that combines deep learning with manifold content. [[cite:&bronstein17_geomet_deep_learn]].
  3. Another take on neural activity as a manifold [[cite:&ebitz21_popul_doctr_cognit_neuros]].
  4. Isomap discussion

* Warming Up :class_questions:
:stateTrait:
The idea behind these questions is twofold. First, I want to suggest that dynamics is implicit in the way we talk about things. It is such a common metaphor that I think we often omit to consider they dynamical when we reflect on the mental. And therefore, the second point is that dynamics can be useful for much more than neural models; it can apply to things that are mental and cognitive too.


I don't think they have any dynamics and it shows how biased psychology is from considering dynamics and dynamical procedures, whether at the test or model levels, when looking at cognitive theories and ideas. 
:END:

1. "What goes around, comes around."
   What does that mean?

   Draw a simple diagram to capture your intution.

2. "The more things change the more they stay the same."
   What does that mean?

   Draw a simple diagram to capture your intution.

3. What is emergence?

4. What is the dynamic content of the psychological terms: /state/ and /trait/?

5. Are mental representations dynamic?

* Mathematical Tools For The Study of Change
  Give an example of a cognitive or neural phenomenon for which you think the right way to think about it is about its dynamics? 

  If you feel that there is a need to incorporate they study of how things change in your area of interest, then you need the tools of *Dynamical Systems*.

** Derivatives and Differential Equations

*** Does Code Matter?
    A principal theme that I have wanted to emphasize, and perhaps failed to fully demonstrate, is the mind, theory, math, /code/ pathway. I feel we have talked about these individuall, but that I have not always been persuasive in establishing their continuity and interdependence. IAMHERE
   


* Companion and Optional Readings
  - Nonlinear Dynamics and Chaos (Strogatz) was recommended to me by several faculty [[cite:&strogatz00_nonlin_dynam_chaos]].
  - A review that blends manifold ideas with dynamic ones [[cite:&vyas20_comput_throug_neural_popul_dynam]] .
  - Generative Dynamics in Brain Networks [[cite:&panahi21_gener_model_brain_dynam]]

* References

[[bibliography:/home/britt/gitRepos/masterBib/bayatt.bib]]

* COMMENT Local Variables
# local variables
# org-latex-pdf-process: '("latexmk -%latex -interaction=nonstopmode -output-directory=%o %f")
# end
