#+bibliography:/home/britt/gitRepos/masterBib/bayatt.bib
#+csl-style: ./j-neurosci.csl


#+Title: Manifold and Dynamics Day
#+Author: Britt Anderson
#+Date: Dec 24, 2021

* Discussion Questions Geometry
1. Can we measure ideas?
2. What is the /shortest/ path between an image of a fish and an image of a man?
3. How do we transit from our current beliefs about the future starting only with our past observations?


* Discussion Questions Dynamics and DEs
1. What is emergence?
2. Is there a feature of differential equations or their dynamic behavior that can be described as emergent?
3. Are there neural or mental phenomena that could thusly be well captured?

** Articles
An introductory [[http://www.faculty.sfasu.edu/judsontw/ode/html-snapshot/firstlook01.html][website]].

An introductory website talking about [[https://www.cfm.brown.edu/people/dobrush/am33/Mathematica/ch2/bifurcation.html][bifurcations]] and using Mathematica, but maybe some can be adapted to other programming languages or computer algebra systems like Maxima.


* Companion and Optional Readings

  1. Generative Dynamics in Brain Networks [[cite:&panahi21_gener_model_brain_dynam]]
     

* References
[[bibliography:/home/britt/gitRepos/masterBib/bayatt.bib]]

#+Title: Geometry and Manifolds


* Just quick notes to get started

** Articles I might find useful

@article{bronstein17_geomet_deep_learn,
  author = {Michael M. Bronstein and Joan Bruna and Yann LeCun and Arthur Szlam and Pierre Vandergheynst},
  title = {Geometric Deep Learning: Going Beyond Euclidean Data},
  journal = {IEEE Signal Processing Magazine},
  volume = {34},
  number = {4},
  pages = {18-42},
  year = {2017},
  doi = {10.1109/msp.2017.2693418},
  url = {https://doi.org/10.1109/msp.2017.2693418},
}

This article talks about the population doctrine in neuroscience, and talks about the new ideas from geometry like the neural manifold.

@article{ebitz21_popul_doctr_cognit_neuros,
  author =	 {R. Becket Ebitz and Benjamin Y. Hayden},
  title =	 {The Population Doctrine in Cognitive Neuroscience},
  journal =	 {Neuron},
  volume =	 109,
  number =	 19,
  pages =	 {3055-3068},
  year =	 2021,
  doi =		 {10.1016/j.neuron.2021.07.011},
  url =		 {https://doi.org/10.1016/j.neuron.2021.07.011},
  DATE_ADDED =	 {Wed Nov 17 20:53:44 2021},
}

Another [[file:local-articles/VyasEtAlAnnRevNeurosci2020.pdf][population dynamics article.]]

[[ https://doi.org/10.1002/wics.128][Geometry in Statistics]]

[[ 
https://journals.aps.org/prx/pdf/10.1103/PhysRevX.8.031003][Geometry of Perceptual Manifolds]]

* Information Geometry

** Articles
   An introduction https://arxiv.org/pdf/1412.5633.pdf (also kept [[file:local-articles/info-geo.pdf][local copy]]).

   
