#+Title: Presentation Day
#+Author: Britt Anderson
#+Date: Winter 2022
#+bibliography:/home/britt/gitRepos/masterBib/bayatt.bib
#+csl-style: ../admin/cambridge-university-press-numeric.csl
#+options: ^:nil


* Outline

The main goal for this day is to be able to have each of the four groups take a 1/2 hour or so to share their project with the rest of the group. The nature of the presentations are pretty open. They can be power points and talking, assignments that we are guided through. It is fine if they require us to read something in advance for a discussion. The main goal we are trying to achieve is to extend the range of topics we are exposed to. Given the time constraint it is unlikely that we will be able to go very deeply into any of these topics in class so there is some expectation that part of the provided material should be a guide for us to continue our studies on our own via readings or on-line material and programming exercises we can pursue.

* Companion and Optional Readings

* References
[[bibliography:/home/britt/gitRepos/masterBib/bayatt.bib]]

